version: '3.4'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    networks:
      - wedding_net
    ports:
    - "15432:5432"

  web:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      RACK_ENV: development
    networks:
      - wedding_net
    ports: 
      - "8080:8080"
    links:
      - db

networks:
  wedding_net:
